### ISSUE TITLE
Make closing the test run optional

### ISSUE THREAD

**Issue by Costas-Zervos-Bose** [mettizik/unitrail#1]
Depending on the teams workflow automatically closing the test run (even when no tests are reported as failing) is undesirable.

**Comment by mettizik** [comment]
@Costas-Zervos-CardinalPeak , Thanks for feedback! Will include this feature as CLI option.

**Comment by mettizik** [comment]
@Costas-Zervos-Bose , this enhancement is implemented in v0.0.4, please run `pip install unitrail --upgrade` and see the `--leaveopen` and `--forceclose` options in CLI
